### PR TITLE
Merge Hydra.Python

### PR DESCRIPTION
**Pull request by Deepanshu2017**

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Thanks very much for the creation of this PR with all work done so far, for the GSoC project!

**Comment by eduardo-rodrigues** [comment]
This should be accepted before Deepanshu submits his final evaluation to GSoC. For me it's ready to go :-).

**Comment by AAAlvesJr** [comment]
It is not necessary actually, but I will accept asap I get home today, by
the end of the Geneve afternoon. No worries.

I think Deepanshu should stop to document by now... Substantial parts of
the code will be redesigned and overwritten soon, because I have improved
hydra quite a lot in some parts and pybind11 will have new version over the
weekend. So I would say project is fine. I would focus in the report.

A.A.

**Comment by eduardo-rodrigues** [comment]
Hi Augusto,

I edited quite a bit of the report in the last few days, mainly tomorrow. From my side I *won’t touch* the report anymore. As I said to Deepanshu on Skype I feel the report is a personal document so I should not “rewrite” it too much to my style. I reckon the present report is very nice.
Do you have anything else on the report?

Code-wise I would actually go a bit further: to be really clean it would even make sense to me to tag a release 0.1.0 of Hydra.Python. The present functionality is already useful and warrants a release. This way it’s even more clear what the outcome of the GSoC project is 😊. I see only prons and no cons with such a milestone and release. Agreed?

Best,
Eduardo

| Eduardo Rodrigues | University of Cincinnati | LHCb Experiment @ CERN & DIANA/HEP | Tel. +41 (0) 22 76 72097 |

**Comment by AAAlvesJr** [comment]
Bonjour,
Je viens de signer la pétition "Sociedade brasileira: Em defesa do direito
de Lula ser candidato a presidente do Brasil" et je souhaitais savoir si
vous voudriez nous aider en ajoutant votre signature.

Notre objectif est d'atteindre 500 000 signatures et nous avons besoin de
plus de soutiens. Pour en savoir plus et pour signer, c'est ici:

http://chng.it/Sd4sRJt2Dv

Merci!
Antonio Augusto

**Pull request merged**
